services:
  hotelier-core-app:
    image: hotelier-core-app
    build:
      context: .
      dockerfile: ./src/hotelier-core-app.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=Host=postgres-db;Port=5432;Database=Hotelier.Core;Username=postgres;Password=password123;Include Error Detail=true
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: hotelier-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: Hotelier.Core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    